### ISSUE TITLE
the driver for RTL8812AU fails to compile for the target "brcm63xx"

### ISSUE THREAD

**Issue by musashino205** [musashino205/lede-source#1]
### Discussion of until now
comments on commit https://github.com/musashino205/lede-source/commit/d573b15ed263e72240a5d61f48ffcd82570f6af8

### Summery
I ([musashino205](https://github.com/musashino205)) fixed a [Makefile for Realtek RTL8812AU chipset](https://gist.github.com/Ins1ghtLabs/c346f7ed4f257d1b4a2d) to pass the compilation for  the target "bcm53xx" and LEDE-Project of current revision in [add_rtl8812au](https://github.com/musashino205/lede-source/tree/add_rtl8812au) branch. 
However, the compilation of the drivers for the target "brcm63xx" using this repository, did not succeed due to some errors.

reported by [linarense](https://github.com/linarense)

### Note
Routers
- bcm53xx ----> BUFFALO WZR-900DHP (SoC: BCM47081, ARM)
- brcm63xx ---> Comtrend AR5387un (SoC: BCM6328, MIPS)

Others

Compile of the driver for RTL8812AU chipset was passed in my (musashino205) environment, but it was not work in the router (WZR-900DHP and WI-U3-866D).

How it is possible to operate if, trying to find ...

**Comment by linarense** [comment]
Thanks!!

Do you think that compilation problems with brcm63xx could be solved modifying Makefile?? Is it necessary to modify your lede sources??

**Comment by musashino205** [comment]
Honestly, I do not know at all at the moment where to find the cause. To have knowledge of Linux that I have too little, because it is not been able to almost understand how the OpenWrt...
In the future, I believe Let's also promoted study on Linux little by little.

When I was a little search, to the router in circulation in the current Japan, one that is equipped with a chipset of target "brcm63xx" it is a no-good. However, since there are many router equipped with the chipset of the same architecture "MIPS", obtain it, I think to try to verify whether through a compilation of against it. Of course, we do not know because the target is different so pass also compiling against "brcm63xx"...

**Comment by musashino205** [comment]
Maybe, the cause of this problem might Endianness.
Endianness of "bcm53xx" is little, but "bcm63xx" is big.
Currently, I write the Endianness with little in the Makefile.

Hasten, to report.

[platforms - OpenWrt](https://dev.openwrt.org/wiki/platforms)

**Comment by linarense** [comment]
I´m trying to compile using the new brand "rtl8812au_forum" but I get the same errors.

**Comment by musashino205** [comment]
Sorry, "rtl8812au_forum" branch is a new branch for another problems.

Please use the "add_rtl8812au" branch, and [#781 line of the Makefile](https://github.com/musashino205/lede-source/blob/add_rtl8812au/package/rtl8812au/Makefile#L781), please be rewritten to
 **"EXTRA_CFLAGS += -DCONFIG_BIG_ENDIAN"**
 from 
**"EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN"**.

After that, please try to compile again.

However, I do not know whether this problem can be solved...

**Comment by linarense** [comment]
Thanks!! Now I can compile without problems bcm63xx version, but my rtl8812au device is not recognized by the router.

**Comment by musashino205** [comment]
Hmm, still do ...
Since the current situation my router (WZR-900DHP) a similar problem has occurred, I'm working on it resolution. However can not be still to work, it is a situation that has become a stalemate.

Because now that so try working to acquaintance also operate the RTL8812AU dongle, we will promote while exchanging him both.

For now, because the problem of this issue is resolved, and then Close. Thanks!

For issues that do not work on the router, I will post a new issue after this.

### Summery of this problem
If you want to compile the RTL8812AU driver for the target "brcm63xx", present in the vicinity of 781 line in the Makefile for RTL8812AU the 
**"EXTRA_CFLAGS + = -DCONFIG_LITTLE_ENDIAN"**, 
rewritten to 
**"EXTRA_CFLAGS + = -DCONFIG_BIG_ENDIAN"**

**Comment by linarense** [comment]
Do you have made any progress about device recognition by the router? Thanks.
